#pragma once

#include "typedefs.hpp"
#include <vector>
#include "functional"

extern u16 LCDC;
extern u16 STAT;
extern u16 SCY;
extern u16 SCX;
extern u16 LY;
extern u16 LYC;
extern u16 DMA;
extern u16 BGP;

class reg {
public:
    u8 hi, lo;
    u16 val();
    void set(u16);
};

class GB_CPU {
public:
    GB_CPU();

    u8 IF;
    u8 IE;

    u16 PC;
    u16 SP;
    u8 IME;

    bool halt;
    bool halt_bug;
    int cycles;
    int timing;
    int count;
    int interrupt_mode;
    int counter;

    u8 TIMA;
    u8 TMA;

    void execute_next_operation();
    void run_opcode(u8 op_code);
    void init_registers_to_skip_boot();
    void print_registers();

    void push_onto_stack(u16 val);
    u16 pop_from_stack();

    void write(u8 val, u16 addr);
    u8 read();
    void init_opcodes();
    void init_decoder();
    void init();

    int get_cycles();
    int get_timing();
    void DMA_routine();

    void cb_not_imp();
    void op_not_imp();
    void STAT();

    void run_cb(u8);

    void inc(int amount);
    void update();
    void overflow();
    void joypadInterrupt();
    void v_blank();
    bool handle_interrupts();

private:
    typedef std::function<void(GB_CPU*)> operation;
    std::vector<std::string> decoder;
    std::vector<operation> op_codes;
    std::vector<operation> cb_codes;
    reg AF, BC, DE, HL;
    void disable_boot_rom();
    void init_codes();
    void push_byte_onto_stack(u8 val);
    void op_code_switch(u8 op_code);
    u8 pop_byte_from_stack();
    bool half_carry_add(u8 a, u8 b);
    bool half_carry_sub(u8 a, u8 b);
    void set_z(bool val);
    void set_n(bool val);
    void set_h(bool val);
    void set_c(bool val);
    bool get_z();
    bool get_n();
    bool get_h();
    bool get_c();

    u8 AssignReg(u8 mask, u8 reg_, bool val);
    u8 RES(u8 bit, u8 reg_);
    void RRA();
    void SBC_generic(u8 sub);
    u8 SLA_generic(u8 val);

    void NOP();
    void LDb_n();
    void LDc_n();
    void LDd_n();
    void LDe_n();
    void LDh_n();
    void LDl_n();
    void LDrr_aa();
    void LDrr_ab();
    void LDrr_ac();
    void LDrr_ad();
    void LDrr_ae();
    void LDrr_ah();
    void LDrr_al();
    void LDrr_aHL();
    void LDrr_aBC();
    void LDrr_aDE();
    void LDrr_ann();
    void LDrr_a_hash();
    void LDrr_bb();
    void LDrr_bc();
    void LDrr_bd();
    void LDrr_be();
    void LDrr_bh();
    void LDrr_bl();
    void LDrr_bHL();
    void LDrr_ba();
    void LDrr_cb();
    void LDrr_cc();
    void LDrr_cd();
    void LDrr_ce();
    void LDrr_ch();
    void LDrr_cl();
    void LDrr_cHL();
    void LDrr_ca();
    void LDrr_db();
    void LDrr_dc();
    void LDrr_dd();
    void LDrr_de();
    void LDrr_dh();
    void LDrr_dl();
    void LDrr_dHL();
    void LDrr_da();
    void LDrr_eb();
    void LDrr_ec();
    void LDrr_ed();
    void LDrr_ee();
    void LDrr_eh();
    void LDrr_el();
    void LDrr_eHL();
    void LDrr_ea();
    void LDrr_hb();
    void LDrr_hc();
    void LDrr_hd();
    void LDrr_he();
    void LDrr_hh();
    void LDrr_hl();
    void LDrr_hHL();
    void LDrr_ha();
    void LDrr_lb();
    void LDrr_lc();
    void LDrr_ld();
    void LDrr_le();
    void LDrr_lh();
    void LDrr_ll();
    void LDrr_lHL();
    void LDrr_la();
    void LDrr_HLb();
    void LDrr_HLc();
    void LDrr_HLd();
    void LDrr_HLe();
    void LDrr_HLh();
    void LDrr_HLl();
    void LDrr_HLn();
    void LDa_c();
    void LDc_a();
    void LDDaHL();
    void LDDHLa();
    void LDI_aHL();
    void LDI_HLa();
    void LDH_nA();
    void LDH_a_ffn();
    void LD_nn_BC();
    void LD_nn_DE();
    void LD_nn_HL();
    void LD_nn_SP();
    void LD_SPHL();
    void LDHL_SPn();
    void LD_nnSP();
    void PUSH_AF();
    void PUSH_BC();
    void PUSH_DE();
    void PUSH_HL();
    void POP_AF();
    void POP_BC();
    void POP_DE();
    void POP_HL();
    void ADD_aa();
    void ADD_ab();
    void ADD_ac();
    void ADD_ad();
    void ADD_ae();
    void ADD_ah();
    void ADD_al();
    void ADD_aH();
    void ADD_a_hash();
    void ADC_generic(u8 add);
    void ADC_aa();
    void ADC_ab();
    void ADC_ac();
    void ADC_ad();
    void ADC_ae();
    void ADC_ah();
    void ADC_al();
    void ADC_aHL();
    void ADC_a_hash();
    void SUB_a();
    void SUB_b();
    void SUB_c();
    void SUB_d();
    void SUB_e();
    void SUB_h();
    void SUB_l();
    void SUB_HL();
    void SUB_hash();
    void SBC_a();
    void SBC_b();
    void SBC_c();
    void SBC_d();
    void SBC_e();
    void SBC_h();
    void SBC_l();
    void SBC_HL();
    void SBC_hash();
    void AND_a();
    void AND_b();
    void AND_c();
    void AND_d();
    void AND_e();
    void AND_h();
    void AND_l();
    void AND_HL();
    void AND_hash();
    void OR_a();
    void OR_b();
    void OR_c();
    void OR_d();
    void OR_e();
    void OR_h();
    void OR_l();
    void OR_HL();
    void OR_hash();
    void XOR_a();
    void XOR_b();
    void XOR_c();
    void XOR_d();
    void XOR_e();
    void XOR_h();
    void XOR_l();
    void XOR_HL();
    void XOR_hash();
    void CP_a();
    void CP_b();
    void CP_c();
    void CP_d();
    void CP_e();
    void CP_h();
    void CP_l();
    void CP_HL();
    void CP_hash();
    void INC_a();
    void INC_b();
    void INC_c();
    void INC_d();
    void INC_e();
    void INC_h();
    void INC_l();
    void INC_HLad();
    void DEC_a();
    void DEC_b();
    void DEC_c();
    void DEC_d();
    void DEC_e();
    void DEC_h();
    void DEC_l();
    void DEC_HLad();
    void ADD_BC();
    void ADD_DE();
    void ADD_HL();
    void ADD_SP();
    void RST_00();
    void RST_08();
    void RST_10();
    void RST_18();
    void RST_20();
    void RST_28();
    void RST_30();
    void RST_38();
    void run_cb();
    void JR_NC();
    void JR_C();
    void JR_NZ();
    void JR_Z();
    void JR_n();
    void JP();
    void JP_NZ();
    void JP_Z();
    void JP_NC();
    void JP_C();
    void JP_HL();
    void LD_HL_a();
    void LD_BC_a();
    void LD_DE_a();
    void LDad_n_a();
    void CALL_nn();
    void CALL_NZ();
    void CALL_Z();
    void CALL_NC();
    void CALL_C();
    void LD_nn_a();
    void RET();
    void RET_NZ();
    void RET_Z();
    void RET_NC();
    void RET_C();
    void RETI();
    void RLA();
    void RLCA();
    u8 RRC_generic(u8 val);
    void RRCA();
    void DI();
    void EI();
    void ADD_n_SP();
    void INC_BC();
    void INC_DE();
    void INC_HL();
    void INC_SP();
    void DEC_BC();
    void DEC_DE();
    void DEC_HL();
    void DEC_SP();
    void HALT();
    void DAA();
    void CPL();
    void CCF();
    void SCF();
    void RR_A();
    void RLC_B();
    void RLC_C();
    void RLC_D();
    void RLC_E();
    void RLC_H();
    void RLC_L();
    void RLC_HL();
    void RLC_A();
    void RRC_B();
    void RRC_C();
    void RRC_D();
    void RRC_E();
    void RRC_H();
    void RRC_L();
    void RRC_HL();
    void RRC_A();
    void SLA_B();
    void SLA_C();
    void SLA_D();
    void SLA_E();
    void SLA_H();
    void SLA_L();
    void SLA_HL();
    void SLA_A();
    u8 SRA_generic(u8 val);
    void SRA_B();
    void SRA_C();
    void SRA_D();
    void SRA_E();
    void SRA_H();
    void SRA_L();
    void SRA_HL();
    void SRA_A();
    void BIT(u8 bit, u8 reg_);
    void BIT_0B();
    void BIT_0C();
    void BIT_0D();
    void BIT_0E();
    void BIT_0H();
    void BIT_0L();
    void BIT_0HL();
    void BIT_0A();
    void BIT_1B();
    void BIT_1C();
    void BIT_1D();
    void BIT_1E();
    void BIT_1H();
    void BIT_1L();
    void BIT_1HL();
    void BIT_1A();
    void BIT_2B();
    void BIT_2C();
    void BIT_2D();
    void BIT_2E();
    void BIT_2H();
    void BIT_2L();
    void BIT_2HL();
    void BIT_2A();
    void BIT_3B();
    void BIT_3C();
    void BIT_3D();
    void BIT_3E();
    void BIT_3H();
    void BIT_3L();
    void BIT_3HL();
    void BIT_3A();
    void BIT_4B();
    void BIT_4C();
    void BIT_4D();
    void BIT_4E();
    void BIT_4H();
    void BIT_4L();
    void BIT_4HL();
    void BIT_4A();
    void BIT_5B();
    void BIT_5C();
    void BIT_5D();
    void BIT_5E();
    void BIT_5H();
    void BIT_5L();
    void BIT_5HL();
    void BIT_5A();
    void BIT_6B();
    void BIT_6C();
    void BIT_6D();
    void BIT_6E();
    void BIT_6H();
    void BIT_6L();
    void BIT_6HL();
    void BIT_6A();
    void BIT_7B();
    void BIT_7C();
    void BIT_7D();
    void BIT_7E();
    void BIT_7H();
    void BIT_7L();
    void BIT_7HL();
    void BIT_7A();
    void RES_0B();
    void RES_0C();
    void RES_0D();
    void RES_0E();
    void RES_0H();
    void RES_0L();
    void RES_0HL();
    void RES_0A();
    void RES_1B();
    void RES_1C();
    void RES_1D();
    void RES_1E();
    void RES_1H();
    void RES_1L();
    void RES_1HL();
    void RES_1A();
    void RES_2B();
    void RES_2C();
    void RES_2D();
    void RES_2E();
    void RES_2H();
    void RES_2L();
    void RES_2HL();
    void RES_2A();
    void RES_3B();
    void RES_3C();
    void RES_3D();
    void RES_3E();
    void RES_3H();
    void RES_3L();
    void RES_3HL();
    void RES_3A();
    void RES_4B();
    void RES_4C();
    void RES_4D();
    void RES_4E();
    void RES_4H();
    void RES_4L();
    void RES_4HL();
    void RES_4A();
    void RES_5B();
    void RES_5C();
    void RES_5D();
    void RES_5E();
    void RES_5H();
    void RES_5L();
    void RES_5HL();
    void RES_5A();
    void RES_6B();
    void RES_6C();
    void RES_6D();
    void RES_6E();
    void RES_6H();
    void RES_6L();
    void RES_6HL();
    void RES_6A();
    void RES_7B();
    void RES_7C();
    void RES_7D();
    void RES_7E();
    void RES_7H();
    void RES_7L();
    void RES_7HL();
    void RES_7A();
    u8 SET(u8 bit, u8 reg_);
    void SET_0B();
    void SET_0C();
    void SET_0D();
    void SET_0E();
    void SET_0H();
    void SET_0L();
    void SET_0HL();
    void SET_0A();
    void SET_1B();
    void SET_1C();
    void SET_1D();
    void SET_1E();
    void SET_1H();
    void SET_1L();
    void SET_1HL();
    void SET_1A();
    void SET_2B();
    void SET_2C();
    void SET_2D();
    void SET_2E();
    void SET_2H();
    void SET_2L();
    void SET_2HL();
    void SET_2A();
    void SET_3B();
    void SET_3C();
    void SET_3D();
    void SET_3E();
    void SET_3H();
    void SET_3L();
    void SET_3HL();
    void SET_3A();
    void SET_4B();
    void SET_4C();
    void SET_4D();
    void SET_4E();
    void SET_4H();
    void SET_4L();
    void SET_4HL();
    void SET_4A();
    void SET_5B();
    void SET_5C();
    void SET_5D();
    void SET_5E();
    void SET_5H();
    void SET_5L();
    void SET_5HL();
    void SET_5A();
    void SET_6B();
    void SET_6C();
    void SET_6D();
    void SET_6E();
    void SET_6H();
    void SET_6L();
    void SET_6HL();
    void SET_6A();
    void SET_7B();
    void SET_7C();
    void SET_7D();
    void SET_7E();
    void SET_7H();
    void SET_7L();
    void SET_7HL();
    void SET_7A();
    u8 RL_generic(u8 val);
    void RL_A();
    void RL_B();
    void RL_C();
    void RL_D();
    void RL_E();
    void RL_H();
    void RL_L();
    void RL_addr_HL();
    u8 SWAP_gen(u8 val);
    void SWAP_a();
    void SWAP_b();
    void SWAP_c();
    void SWAP_d();
    void SWAP_e();
    void SWAP_h();
    void SWAP_l();
    void SWAP_HL();
    void RES_0_a();
    void SRL_B();
    void SRL_C();
    void SRL_D();
    void SRL_E();
    void SRL_H();
    void SRL_L();
    void SRL_HL();
    void SRL_A();
    void CB_RR_A();
    void RR_B();
    void RR_C();
    void RR_D();
    void RR_E();
    void RR_H();
    void RR_L();
    void RR_HL();
};

namespace RUPS {
    extern u8 IF;
    extern u8 IE;
}
