name: emsdk
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: mymindstorm/setup-emsdk@v11

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          emcmake cmake .
          emmake make

      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build
