name: emsdk
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: mymindstorm/setup-emsdk@v11

      - name: Build
        run: |
          mkdir build
          emcmake cmake .
          emmake make

      - name: Tests
        run: |
          node ./src/tests.js
