name: emsdk
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  EM_VERSION: 3.1.47
  EM_CACHE_FOLDER: "emsdk-cache"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{ runner.os }}

      - uses: mymindstorm/setup-emsdk@v11
        with:
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - name: Build
        run: |
          mkdir build
          emcmake cmake .
          emmake make
